### PR TITLE
gtk/templates: Add missing traits for TemplateChild

### LINKED ISSUE #1842: TemplateChild doesn't work as property
**Bug description**

When using this minimal example I get

> the trait bound `gtk4::TemplateChild<gtk4::Widget>: ToValue` is not satisfied

I need to specify the property as

`#[property(get = |s: &&Self| (*s.test_widget).clone(), type = gtk4::Widget)]`

to make it work.

**test_widget.rs**

```rust
use gtk4::glib;
use gtk4::prelude::*;
use gtk4::subclass::prelude::*;

mod imp {
    use super::*;

    #[derive(Default, glib::Properties, gtk4::CompositeTemplate)]
    #[template(file = "test_widget.ui")]
    #[properties(wrapper_type = super::TestWidget)]
    pub struct TestWidget {
        #[property(get)]
        #[template_child]
        test_widget: TemplateChild<gtk4::Widget>,
    }

    #[glib::object_subclass]
    impl ObjectSubclass for TestWidget {
        const NAME: &'static str = "TestWidget";
        type Type = super::TestWidget;
        type ParentType = gtk4::Widget;

        fn class_init(klass: &mut Self::Class) {
            klass.bind_template();
        }

        fn instance_init(obj: &glib::subclass::InitializingObject<Self>) {
            obj.init_template();
        }
    }

    #[glib::derived_properties]
    impl ObjectImpl for TestWidget {}
    impl WidgetImpl for TestWidget {}
    impl TestWidget {}
}

glib::wrapper! {
    pub struct TestWidget(ObjectSubclass<imp::TestWidget>)
    @extends gtk4::Widget;
}
```

**test_widget.ui**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<interface>
  <template class="TestWidget" parent="GtkWidget">
    <child>
      <object class="GtkWidget" id="widget" />
    </child>
  </template>
</interface>
```

Apparently this worked once, considering #1495 was merged, but something must have either regressed, or it never really worked after all :smile:

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Fixes #1842

Only compile tested

cc @felinira @sdroege

### CODE REVIEW

**Review by sdroege — APPROVED** [review]

File: gtk4/src/subclass/widget.rs [hunk 1]
```diff
@@ -1245,6 +1245,43 @@ where
...
+where
+    T: ObjectType + FromGlibPtrNone<*mut <T as ObjectType>::GlibType>,
+{
+    type Checker = glib::value::GenericValueTypeChecker<T>;
+
+    #[inline]
+    unsafe fn from_value(value: &'a glib::Value) -> Self {
+        skip_assert_initialized!();
+        TemplateChild {
+            ptr: T::from_value(value).as_ptr(),
```
Comment (sdroege) [inline gtk4/src/subclass/widget.rs:1280]: Actually no, this looks wrong. The pointers becomes invalid after this call, you need `into_glib_ptr()` or so but then `TemplateChild` has no `Drop`...

Comment (bilelmoussaoui) [reply gtk4/src/subclass/widget.rs:1280]: Right because Gtk is keeping the ref of the child and drops it itself. If we do implement Drop, we would have to some bool to identify whether we should unref the ptr or not. Sounds a bit hackish but no ideas how to do this properly :)

Comment (sdroege) [reply gtk4/src/subclass/widget.rs:1280]: Do we need the `FromValue` impl?

Comment (bilelmoussaoui) [reply gtk4/src/subclass/widget.rs:1280]: Yes. Otherwise it can't really be a property

Comment (sdroege) [reply gtk4/src/subclass/widget.rs:1280]: Do we want writable properties to be possible for this? Seems strange to me. Readonly seems to make sense.

Comment (bilelmoussaoui) [reply gtk4/src/subclass/widget.rs:1280]: Well, you want to have writable properties yes. All container widgets nowadays have a "child" property that is readwrite.

Comment (sdroege) [reply gtk4/src/subclass/widget.rs:1280]: Oh I see. Well, then you'll need a drop boolean :)

Comment (bilelmoussaoui) [reply gtk4/src/subclass/widget.rs]: Done that in the latest push

File: gtk4/src/subclass/widget.rs [hunk 2]
```diff
@@ -1211,12 +1211,12 @@ pub unsafe trait WidgetClassExt: ClassStruct {
 unsafe impl<T: ClassStruct> WidgetClassExt for T where T::Type: WidgetImpl {}
 
 #[derive(Debug, PartialEq, Eq)]
-#[repr(transparent)]
```
[the remark this answers is not in the document]
Comment (sdroege) [reply gtk4/src/subclass/widget.rs:1214]: I hope nothing was relying on it being the same representation as `T` :)

[the remark this answers is not in the document]
Comment (sdroege) [reply gtk4/src/subclass/widget.rs:1214]: Maybe this needs to be repr-C now so that we at least guarantee that the pointer is stored at the beginning? How is GtkBuilder filling this?

[the remark this answers is not in the document]
Comment (bilelmoussaoui) [reply gtk4/src/subclass/widget.rs:1214]: > Maybe this needs to be repr-C now so that we at least guarantee that the pointer is stored at the beginning? How is GtkBuilder filling this?

By calling gtk_widget_class_bind_template_child_full, which is used from rust with bind_template_child_with_offset. But yes, maybe it should be repr-C.

[the remark this answers is not in the document]
Comment (sdroege) [reply gtk4/src/subclass/widget.rs:1214]: Yes, it currently works with the offset to `TemplateChild` so you need to make it repr-C at least

[the remark this answers is not in the document]
Comment (bilelmoussaoui) [reply gtk4/src/subclass/widget.rs:1214]: Done, let us wait and see if @felinira got whatever use case they have working with this patch first. I tested it locally by changing one of the examples but still

[the remark this answers is not in the document]
Comment (bilelmoussaoui) [reply gtk4/src/subclass/widget.rs:1214]: > I'm a little surprised why this needs a FromValue implementation though. Isn't this readonly?

The requirement seems to come from `ObjectExt::property`
```rust
fn property<V: for<'b> FromValue<'b> + 'static>(&self, property_name: &str) -> V;
```

So it is expected? not sure why you are surprised about it, unless you meant the ToValue? in such case, FromValue, requires ValueType, which itself requires ToValue....

**Comment by bilelmoussaoui** [comment]
As this fixes the issue, let us land it already, any further fixes could be done separately
