### PR TITLE
fix(event_controller): set_static_name UAF fixed, name now has static lifetime

### LINKED ISSUE #2053: EventControllerKey.set_static_name SEGFAULT
**Bug description**

When I use the method `EventControllerKey.set_static_name` with a string literal param, then I add this controller to the window of the app, and then I open the GTK Inspector and visit the `Controllers` tab, I see one controller (I pressume it's the one I setted) with garbage characters (non-UTF-8), after navigating for a while, the application crashes with the Segmentation Fault (core dump) message.

I think it's because of the lifetime of the param not being `'static` and the compiler optimizing it somehow.
```rust
fn set_static_name(name: Option<&str>) { ... }
```

**Please provide a code sample as small as possible which reproduces the bug.**
```rust
fn main() -> glib::ExitCode {
    let app: gtk::Application = glib::Object::builder().build();

    app.connect_activate(|app| {
        let window = gtk::ApplicationWindow::new(app);
        let key_controller = gtk::EventControllerKey::new();
        key_controller.set_static_name(Some("foo"));
        window.add_controller(key_controller);
        window.present()
    });

    app.run()
}
```

**Backtrace**

~~N/A because it doesn't panic, the process just get killed by the OS.~~

So the error is non-deterministic, I tried another run and the app didn't crash at any moment, but the garbage characters were still there

### PR DESCRIPTION
**Pull request by otaxhu**
Fixes #2053

### CODE REVIEW

**Comment by otaxhu** [comment]
Ready for review @bilelmoussaoui

File: gtk4/src/event_controller.rs [hunk 1]
```diff
@@ -0,0 +1,24 @@
+// Take a look at the license at the top of the repository in the LICENSE file.
+
+#[allow(unused_imports)]
+use glib::translate::*;
+
+use crate::prelude::*;
+#[allow(unused_imports)]
+use crate::{ffi, EventController};
```
Comment (bilelmoussaoui) [inline gtk4/src/event_controller.rs:8]:
```suggestion
#[cfg(feature = "v4_8")]
use glib::translate::*;

#[cfg(feature = "v4_8")]
use crate::{ffi, prelude::*, EventController};
```

File: gtk4/Gir.toml [hunk 2]
```diff
@@ -1174,6 +1173,15 @@ status = "generate"
...
     manual = true # upcast to Entry
 
+[[object]]
+name = "Gtk.EventController"
+status = "generate"
+manual_traits = ["EventControllerExtManual"]
+    [[object.function]]
+    name = "set_static_name"
+    manual = true # to make use of a static lifetimed string
+    doc_trait_name = "EventControllerExtManual"
```
Comment (bilelmoussaoui) [inline gtk4/Gir.toml:1183]:
```suggestion
```

**Comment by bilelmoussaoui** [comment]
Please rebase for the CI to pass.

**Comment by bilelmoussaoui** [comment]
& squash the commits into a single one.

File: gtk4/src/event_controller.rs (hunk 1 above)
Comment (otaxhu) [reply gtk4/src/event_controller.rs:8]: prelude::* needs to be in scope in order for `IsA<EventController>` to work

**Review by bilelmoussaoui — APPROVED** [review]

File: gtk4/src/event_controller.rs [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+
+#[cfg(feature = "v4_8")]
+use crate::ffi;
+use crate::{prelude::*, EventController};
+
+pub trait EventControllerExtManual: IsA<EventController> + 'static {
+    #[cfg(feature = "v4_8")]
+    #[cfg_attr(docsrs, doc(cfg(feature = "v4_8")))]
+    #[doc(alias = "gtk_event_controller_set_static_name")]
+    fn set_static_name(&self, name: Option<&'static str>) {
```
Comment (sdroege) [inline gtk4/src/event_controller.rs:14]:
```suggestion
    fn set_static_name(&self, name: Option<&'static glib::GStr>) {
```

it needs to be a NUL-terminated string, and `&str` is not

Comment (sdroege) [reply gtk4/src/event_controller.rs:14]:
```suggestion
    fn set_static_name(&self, name: impl Into<Option<&'static glib::GStr>>) {
```

if you want it to be a bit more generic

Comment (otaxhu) [reply gtk4/src/event_controller.rs:14]: https://gtk-rs.org/gtk-rs-core/stable/latest/docs/src/glib/translate.rs.html#558-590

That's already covered by the function `to_glib_none`

Comment (otaxhu) [reply gtk4/src/event_controller.rs:14]: It's better to have API simplicity and accept a `&str`.

Comment (sdroege) [reply gtk4/src/event_controller.rs:14]: This doesn't fix anything though. The temporary string created by `to_glib_none()` is freed and then you have a dangling pointer inside GTK.

Comment (otaxhu) [reply gtk4/src/event_controller.rs:14]: Do you think we should ***remove*** this function and encourage people to use `set_name`?

The reason being that API users will have to convert the string into a `CStr` then into a `GStr`, resulting in very verbose code.

`GStr` doesn't have `From` traits, but it has `TryFrom<&'a CStr>`, so even if the function signature is `fn set_static_name(name: impl Into<Option<&'static glib::GStr>>)` it won't work.

An example of calling `set_static_name`:
```rust
let controller: gtk::EventController = ...;
controller.set_static_name(Some(c"Hello".try_into().unwrap()));
```

Doing so will represent a breaking change

Comment (otaxhu) [reply gtk4/src/event_controller.rs:14]: Nobody has reported this error since 3 years ago, so I think is less of a problem to break the API.

https://github.com/gtk-rs/gtk4-rs/blame/main/gtk4/src/auto/event_controller.rs#L148

**Comment by otaxhu** [comment]
PR converted to draft due what @sdroege commented https://github.com/gtk-rs/gtk4-rs/pull/2056#discussion_r2094142830

File: gtk4/src/event_controller.rs (hunk 3 above)
Comment (sdroege) [reply gtk4/src/event_controller.rs:14]: You can do `glib::gstr!("blablabla")` to get a `&'static glib::GStr`

Comment (otaxhu) [reply gtk4/src/event_controller.rs:14]: Ok, I'm gonna add that to the PR and re-open it
