### PR TITLE
gtk: fix measure & add a layout manager example

### LINKED ISSUE #222: Investigate WidgetImpl::measure
The current function takes &mut, while the default WidgetExt::measure just returns `(i32, i32, i32, i32)`. We should check whether it makes sense to change `WidgetImpl::measure` signature or not.

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
This PR fixes #222 and adds a custom layout manager example which is mostly a port from the gtk4-demo

screenshot

### CODE REVIEW

File: examples/custom_layout_manager/custom_layout.rs [hunk 1]
```diff
@@ -0,0 +1,186 @@
+use crate::TOTAL_COLORS;
+use gtk::glib;
+use gtk::prelude::*;
+use gtk::subclass::prelude::*;
+
+const N_GRID_COLUMNS: u32 = 4;
+
+mod imp {
```
Comment (sdroege) [inline examples/custom_layout_manager/custom_layout.rs:8]: Why not move this into a separate file instead of an inline module? :)

File: examples/custom_layout_manager/custom_layout.rs [hunk 2]
```diff
@@ -0,0 +1,186 @@
...
+    pub struct CustomLayout {
+        pub position: Cell<f64>,
+        pub child_pos: RefCell<Vec<i32>>,
+    }
+    impl Default for CustomLayout {
+        fn default() -> Self {
+            let mut positions = Vec::new();
+            for i in 0..TOTAL_COLORS {
+                positions.push(i);
+            }
```
Comment (sdroege) [inline examples/custom_layout_manager/custom_layout.rs:21]:
```rust
let positions = (0..TOTAL_COLORS).collect::<Vec<_>>();
```
would be shorter :)

File: examples/custom_layout_manager/custom_layout.rs [hunk 3]
```diff
@@ -0,0 +1,186 @@
...
+            let mut child = widget.first_child().unwrap();
+            loop {
+                if !child.should_layout() {
+                    continue;
+                }
+
+                let (child_min, child_nat, _, _) = child.measure(orientation, -1);
+                min_size = min_size.max(child_min);
+                nat_size = nat_size.max(child_nat);
+                if child.next_sibling().is_none() {
```
Comment (sdroege) [inline examples/custom_layout_manager/custom_layout.rs:65]:
```rust
if let Some(next_child) = child.next_sibling() {
    child = next_child;
} else {
    break;
}
```

File: examples/custom_layout_manager/custom_layout.rs [hunk 4]
```diff
@@ -0,0 +1,186 @@
...
+            let mut child = widget.first_child().unwrap();
+            loop {
+                if !child.should_layout() {
+                    continue;
+                }
+
+                let (child_req, _) = child.preferred_size();
+                child_width = child_width.max(child_req.width);
+                child_height = child_height.max(child_req.height);
+                if child.next_sibling().is_none() {
```
Comment (sdroege) [inline examples/custom_layout_manager/custom_layout.rs:101]: Same here

File: examples/custom_layout_manager/custom_layout.rs [hunk 5]
```diff
@@ -0,0 +1,186 @@
...
+                    &gtk::Allocation {
+                        x: x as i32,
+                        y: y as i32,
+                        width: child_width,
+                        height: child_height,
+                    },
+                    -1,
+                );
+                i += 1;
+                if child.next_sibling().is_none() {
```
Comment (sdroege) [inline examples/custom_layout_manager/custom_layout.rs:142]: And here

File: examples/custom_layout_manager/custom_layout_child.rs [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+glib::wrapper! {
+    pub struct CustomLayoutChild(ObjectSubclass<imp::CustomLayoutChild>)
+        @extends gtk::Widget;
+}
+
+impl CustomLayoutChild {
+    pub fn new(color: gdk::RGBA) -> Self {
+        let widget = glib::Object::new(&[]).expect("Failed to create CustomLayoutChild");
+        let inner = imp::CustomLayoutChild::from_instance(&widget);
+        inner.color.replace(color);
```
Comment (sdroege) [inline examples/custom_layout_manager/custom_layout_child.rs:66]: This should really be a construct-only property :)

File: examples/custom_layout_manager/main.rs [hunk 7]
```diff
@@ -0,0 +1,55 @@
...
+    "yellow",
+    "firebrick",
+    "aqua",
+    "purple",
+    "tomato",
+    "pink",
+    "thistle",
+    "maroon",
+];
+const TOTAL_COLORS: i32 = 16;
```
Comment (sdroege) [inline examples/custom_layout_manager/main.rs:27]:
```suggestion
const TOTAL_COLORS: i32 = COLORS.len();
```

File: gtk4/src/subclass/layout_manager.rs [hunk 8]
```diff
@@ -29,7 +29,10 @@ pub trait LayoutManagerImpl: LayoutManagerImplExt + ObjectImpl {
         self.parent_create_layout_child(layout_manager, widget, for_child)
     }
 
-    fn layout_child_type() -> glib::Type;
+    /// Only set if the child implemented LayoutChildImpl
+    fn layout_child_type() -> Option<glib::Type> {
+        None
```
Comment (sdroege) [inline gtk4/src/subclass/layout_manager.rs:34]: Should still call the parent one :)

**Review by sdroege — COMMENTED** [review]
Looks good otherwise, nice example :)

File: examples/custom_layout_manager/custom_layout.rs (hunk 1 above)
Comment (bilelmoussaoui) [reply examples/custom_layout_manager/custom_layout.rs:8]: Because none of the examples in gtk4-rs does that and didn't want to have only one that's different than others. We should probably do that for all of them though but I wouldn't do it as part of this;

cc @Hofer-Julian as you have done something similar for gtk-rs

File: examples/custom_layout_manager/custom_layout.rs (hunk 2 above)
Comment (bilelmoussaoui) [reply examples/custom_layout_manager/custom_layout.rs:21]: Nice :) thanks!

File: examples/custom_layout_manager/custom_layout.rs (hunk 3 above)
Comment (bilelmoussaoui) [reply examples/custom_layout_manager/custom_layout.rs:65]: Oups, those are reasons to not write code that late at night :)

File: examples/custom_layout_manager/custom_layout_child.rs (hunk 6 above)
Comment (bilelmoussaoui) [reply examples/custom_layout_manager/custom_layout_child.rs:66]: Does it has to be a property though? :)

File: gtk4/src/subclass/layout_manager.rs (hunk 8 above)
Comment (bilelmoussaoui) [reply gtk4/src/subclass/layout_manager.rs:34]: There's no parent one it's not a method but it sets the type on the Class struct with
```
        if let Some(type_) = T::layout_child_type() {
            klass.layout_child_type = type_.to_glib();
        }
```
Setting a `layout_child_type` to a widget instead of LayoutChild requires having `layout-child` property which is the widget; not something the user often has to do that's why it's None by default

File: examples/custom_layout_manager/custom_layout.rs (hunk 1 above)
Comment (Hofer-Julian) [reply examples/custom_layout_manager/custom_layout.rs:9]: I can adapt them.
Want to open an issue and assign it to me?

File: examples/custom_layout_manager/custom_layout_child.rs (hunk 6 above)
Comment (bilelmoussaoui) [reply examples/custom_layout_manager/custom_layout_child.rs:66]: Updated as we don't have an example with a boxed property :-)

File: examples/custom_layout_manager/custom_layout.rs (hunk 1 above)
Comment (bilelmoussaoui) [reply examples/custom_layout_manager/custom_layout.rs:9]: Done, thanks Julian! :)

File: examples/custom_layout_manager/custom_layout_child.rs (hunk 6 above)
Comment (sdroege) [reply examples/custom_layout_manager/custom_layout_child.rs]: > Does it has to be a property though? :)

Well, constructors should (ideally!) only call `glib::Object::new` and nothing else :)

**Review by sdroege — APPROVED** [review]
