### PR TITLE
gtk: use ToVariant for Actionable::set_action_target

### LINKED ISSUE #767: [BUG] Error when using ActionableExtManual::set_action_target
I tried to use `ActionableExtManual::set_action_target` like this:

```rust
button.set_action_target(&string));
```

Every time I get these errors in the logs:

```shell
GLib-CRITICAL **: 16:31:11.017: '%s' is not a valid GVariant format string
GLib-CRITICAL **: 16:31:11.017: g_variant_new_va: assertion 'valid_format_string (format_string, !endptr, NULL)' failed
```
It works however with `ActionableExt::set_action_target_value`, like this:

```rust
button.set_action_target_value(Some(&string.to_variant()));
```

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Fixes #767

### CODE REVIEW

File: gtk4/src/actionable.rs [hunk 1]
```diff
@@ -1,25 +1,22 @@
...
 use glib::translate::*;
-use libc::c_char;
+use glib::{IsA, ToVariant};
 
 // rustdoc-stripper-ignore-next
 /// Trait containing manually implemented methods of [`Actionable`](crate::Actionable).
 pub trait ActionableExtManual: 'static {
     #[doc(alias = "gtk_actionable_set_action_target")]
-    fn set_action_target(&self, string: &str);
+    fn set_action_target<V: ToVariant>(&self, string: &V);
```
Comment (sdroege) [inline gtk4/src/actionable.rs:11]:
```suggestion
    fn set_action_target<V: ToVariant>(&self, target: &V);
```

Not really a string, is it? :)

Comment (sdroege) [reply gtk4/src/actionable.rs:11]: But also ...

File: gtk4/src/actionable.rs [hunk 2]
```diff
@@ -1,25 +1,22 @@
...
 }
 
 impl<O: IsA<Actionable>> ActionableExtManual for O {
-    fn set_action_target(&self, string: &str) {
-        let string: Stash<*const c_char, _> = string.to_glib_none();
+    fn set_action_target<V: ToVariant>(&self, string: &V) {
```
Comment (sdroege) [inline gtk4/src/actionable.rs:15]:
```suggestion
    fn set_action_target<V: ToVariant>(&self) {
```

You're not really using the value itself...

File: gtk4/src/actionable.rs [hunk 3]
```diff
@@ -1,25 +1,22 @@
...
         unsafe {
             ffi::gtk_actionable_set_action_target(
                 self.as_ref().to_glib_none().0,
-                b"%s\0".as_ptr() as *const c_char,
-                string.0,
+                string.to_variant().type_().as_str().to_glib_none().0,
```
Comment (sdroege) [inline gtk4/src/actionable.rs:19]: ... and can do just

```suggestion
                V::static_variant_type.to_glib_none().0,
```

Comment (sdroege) [reply gtk4/src/actionable.rs:19]: However I think this is wrong. This function wants a variant format string and then the values of the variant.

I think you want to call `gtk_actionable_set_action_target_value(v.to_variant().to_glib_none().0)`. Note that this function's parameter is `nullable`.

**Review by sdroege — CHANGES_REQUESTED** [review]

**Review by sdroege — APPROVED** [review]
