### PR TITLE
gdk: Rename `GdkCairoContextExt::set_source_{rgba => color}`

### LINKED ISSUE #1469: GdkCairoContextExt::set_source_rgba clashes with Context::set_source_rgba
**Bug description**

It is not possible current to call `GdkCairoContextExt::set_source_rgba` without having to qualify it.

This doesn't compile:
```rust
cr.set_source_rgba(color); // Where set_source_rgba is from GdkCairoContextExt
```

It has to be the following, which is verbose:
```rust
GdkCairoContextExt::set_source_rgba(self, color);
```

One possible solution is to rename `GdkCairoContextExt::set_source_rgba`  to something like `GdkCairoContextExt::set_source_color` .

**Backtrace**

Not applicable

### PR DESCRIPTION
**Pull request by RealKC**
This is a breaking change

Fixes #1469

### CODE REVIEW

**Comment by RealKC** [comment]
CI failures seem unrelated, I did not modify gsk. I think Bilal has a PR that would fix it?

**Comment by bilelmoussaoui** [comment]
The CI should pass once I merged #1475

File: gdk4/src/cairo_interaction.rs [hunk 1]
```diff
@@ -45,7 +45,7 @@ pub trait GdkCairoContextExt {
     );
 
     #[doc(alias = "gdk_cairo_set_source_rgba")]
```
Comment (bilelmoussaoui) [inline gdk4/src/cairo_interaction.rs:47]: Please add a doc alias for set_source_rgba

Comment (bilelmoussaoui) [reply gdk4/src/cairo_interaction.rs:47]: Also we should probably move the functions implementations to the trait definition and seal it. Would you mind doing that in a separate commit here? :)

Comment (RealKC) [reply gdk4/src/cairo_interaction.rs:47]: Sure

File: gdk4/src/cairo_interaction.rs [hunk 2]
```diff
@@ -84,27 +57,48 @@ impl GdkCairoContextExt for Context {
...
         }
     }
 }
+
+impl GdkCairoContextExt for Context {}
+
+mod sealed {
+    use cairo::Context;
+
+    pub trait Sealed {
```
Comment (RealKC) [inline gdk4/src/cairo_interaction.rs:95]: Is there any reason gdk4 doesn't enable the `use_glib` feature of cairo? This would allow rewriting this as `pub trait Sealed: IntoGlibPtr<*mut cairo::cairo_t>` I think

Comment (RealKC) [reply gdk4/src/cairo_interaction.rs:95]: Nevermind

Comment (bilelmoussaoui) [reply gdk4/src/cairo_interaction.rs:95]: Tbh, i do believe we should enable that. Just no one ever thought of doing so :)

Comment (RealKC) [reply gdk4/src/cairo_interaction.rs:95]: Oh, then I enabled it in 75dfa9e4b32a25fe70587dfd94b36bfb9c97eb84 :)

File: gdk4/Cargo.toml [hunk 3]
```diff
@@ -29,7 +29,7 @@ rustc-args = ["--cfg", "docsrs"]
 rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]
 
 [dependencies]
-cairo-rs = {git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.19"}
+cairo-rs = {git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.19", features = ["use_glib"]}
```
Comment (bilelmoussaoui) [inline gdk4/Cargo.toml:32]: Can you also enable it in other crates as well?

**Review by bilelmoussaoui — COMMENTED** [review]
Otherwise lgtm, thanks a lot

**Review by bilelmoussaoui — APPROVED** [review]
